# Generated by Django 3.2.6 on 2021-08-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranteuser',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Número de teléfono'),
        ),
    ]
